version: '3.9'
services:
  ai-baseballcoach:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Tokyo
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - AUTH0_DOMAIN
      - APP_SECRET_KEY
      - HUGGINGFACE_TOKEN
    tty: true
