name: ai-baseballcoach
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy=1.20.*
  - pandas=1.2.*
  - pytest
  - pytest-cov
  - pytest-mock
  - yamllint
  - black
  - pylint
  - flake8
  - setuptools>=65.5.1
  - pip:
      - pytest-watch
      - transformers
      - pre-commit
      - torch
