name: Terraform Lint and Format Check

on:
  pull_request:
    paths:
      - 'tool/infrastructure/**/*.tf'
  push:
    branches:
      - main
    paths:
      - 'tool/infrastructure/**/*.tf'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tool/infrastructure
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.2"

      - name: Setup Terraform linter
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest

      - name: Show tflint version
        run: tflint --version

      - name: Initialize tflint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize Terraform workspace
        id: init
        run: terraform init

      - name: Check Terraform formatting
        id: format
        run: make format_check

      - name: Validate Terraform configuration
        id: lint
        run: make lint
